# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'KakaoFaceLogin' do

use_frameworks!

pod 'Firebase'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'FBSDKCoreKit'
pod 'FBSDKShareKit'
pod 'FBSDKLoginKit'


end

target 'KakaoFaceLoginTests' do

end

target 'KakaoFaceLoginUITests' do

end

