# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'GoogleLogin' do

pod 'Firebase'
pod 'Firebase/Core'
pod 'Firebase/Auth'
pod 'GoogleSignIn'

end

target 'GoogleLoginTests' do

end

target 'GoogleLoginUITests' do

end

